Move quirks initialization to the hid_pidff_init function
JacKeTUs/universal-pidff pull request #12
Opened 2024-07-15 15:17 UTC by JacKeTUs

2024-07-15 15:18 UTC, JacKeTUs commented
@Lawstorant, please check if Moza wheelbase initializes for you

2024-07-16 09:17 UTC, Lawstorant commented on hid-pidff.h
> +int hid_pidff_init(struct hid_device *hid, const struct hid_device_id *id);
This conflicts with in-kernel pidff init function. Maybe rename it to `hid_new_pidff_init`?

2024-07-16 09:19 UTC, Lawstorant requested changes

2024-07-16 09:19 UTC, Lawstorant commented on hid-pidff.c
> +int hid_pidff_init(struct hid_device *hid, const struct hid_device_id *id)
Just a pointer to function definition

2024-07-16 09:19 UTC, Lawstorant commented on hid-pidff-wrapper.c
> +	ret = hid_pidff_init(hdev, id);
Pointer to function reference

2024-07-16 09:20 UTC, Lawstorant commented
Apart from this one issue, it compiles successfully after changing the name of this function and initializes MOZA FFB properly.

2024-07-16 09:29 UTC, JacKeTUs commented on hid-pidff.h
> +int hid_pidff_init(struct hid_device *hid, const struct hid_device_id *id);
yep, let's rename it for now
Now pidff driver has hardcoded descriptor values and we can't set any of specific descriptors as non-mandatory, that's why we need the quirks. 

ff_init function from driver (`include/linux/hid.h:1213`) does not expect any quirks from pidff, it expects USB quirks, a different type

2024-07-16 09:32 UTC, Lawstorant commented on hid-pidff.h
> +int hid_pidff_init(struct hid_device *hid, const struct hid_device_id *id);
Yup, I give up on upstream pidff compatibility for now. Apart from pushing the 0 length issue upstream, I don't think we will achieve much more there. At least this give us more freedom

2024-07-16 09:33 UTC, Lawstorant approved these changes
LGTM

2024-07-16 09:37 UTC, merged