Added VRS DirectForce Pro
JacKeTUs/universal-pidff pull request #9
Opened 2024-07-15 01:38 UTC by JacKeTUs

From https://github.com/JacKeTUs/vrs-ff

2024-07-15 02:02 UTC, JacKeTUs commented
@LithiumFox, as promised, i merged multiple versions of one driver into one repository. That universal one should cover all boxes for most of wheelbases, including VRS. Please, test this with your VRS Wheelbase. If everything OK, i will archive vrs-ff and we will migrate users to this driver :smiley:

2024-07-15 08:27 UTC, Lawstorant requested changes

2024-07-15 08:27 UTC, Lawstorant commented on hid-pidff-wrapper.c
> +	{ HID_USB_DEVICE(USB_VENDOR_ID_MOZA, USB_DEVICE_ID_MOZA_R16_R21),
R16_R21 duplication

2024-07-15 15:30 UTC, JacKeTUs commented
Need to wait for https://github.com/JacKeTUs/universal-pidff/pull/12 to merge

2024-10-17 12:13 UTC, ccalhoun1999 commented
I've managed to build and test this branch on my vrs directforce pro with no issues.

2024-10-17 14:01 UTC, merged